package models

type Stats struct {
	Def                   int `json:"def,omitempty"`
	Dmg                   int `json:"dmg,omitempty"`
	Delay                 int `json:"delay,omitempty"`
	Hp                    int `json:"hp,omitempty"`
	Mp                    int `json:"mp,omitempty"`
	Str                   int `json:"str,omitempty"`
	Dex                   int `json:"dex,omitempty"`
	Vit                   int `json:"vit,omitempty"`
	Agi                   int `json:"agi,omitempty"`
	Int                   int `json:"int,omitempty"`
	Mnd                   int `json:"mnd,omitempty"`
	Chr                   int `json:"chr,omitempty"`
	WSAccuracy            int `json:"wSAccuracy,omitempty"`
	MagicAccuracy         int `json:"magicAccuracy,omitempty"`
	MagicDefBonus         int `json:"magicDefBonus,omitempty"`
	MagicBurstBonus       int `json:"magicBurstBonus,omitempty"`
	MagicAttackBonus      int `json:"magicAttackBonus,omitempty"`
	MagicDamage           int `json:"magicDamage,omitempty"`
	SpellInterruptionRate int `json:"spellInterruptionRate,omitempty"`
	Refresh               int `json:"refresh,omitempty"`
	RangedAccuracy        int `json:"rangedAccuracy,omitempty"`
	RangedAttack          int `json:"rangedAttack,omitempty"`
	PhysicalAccuracy      int `json:"physicalAccuracy,omitempty"`
	PhysicalAttack        int `json:"physicalAttack,omitempty"`
	DoubleAttack          int `json:"doubleAttack,omitempty"`
	TripleAttack          int `json:"tripleAttack,omitempty"`
	QuadripleAttack       int `json:"quadripleAttack,omitempty"`
	GearHaste             int `json:"gearHaste,omitempty"`
	CurePot               int `json:"curePot,omitempty"`
	CounterRate           int `json:"counterRate,omitempty"`
	DualWield             int `json:"dualWield,omitempty"`
	Regen                 int `json:"regen,omitempty"`
	Zanshin               int `json:"zanshin,omitempty"`
	CureCasting           int `json:"cureCasting,omitempty"`
	ConserveMP            int `json:"conserveMP,omitempty"`
	BloodPactDelay        int `json:"bloodPactDelay,omitempty"`
	Cursna                int `json:"cursna,omitempty"`
	SubtleBlow            int `json:"subtleBlow,omitempty"`
	StoreTP               int `json:"storeTP,omitempty"`
	Enmity                int `json:"enmity,omitempty"`
	MAB                   int `json:"mAB,omitempty"`
	MagicEvasion          int `json:"magicEvasion,omitempty"`
	PhysicalEvasion       int `json:"physicalEvasion,omitempty"`
	Mdt                   int `json:"mdt,omitempty"`
	Pdt                   int `json:"pdt,omitempty"`
	Dt                    int `json:"dt,omitempty"`
	ShieldSkill           int `json:"shieldSkill,omitempty"`
	GeomancySkill         int `json:"geomancySkill,omitempty"`
	HandbellSkill         int `json:"handbellSkill,omitempty"`
	SummoningSkill        int `json:"summoningSkill,omitempty"`
	BlueSkill             int `json:"blueSkill,omitempty"`
	DivineSkill           int `json:"divineSkill,omitempty"`
	HealingSkill          int `json:"healingSkill,omitempty"`
	DarkSkill             int `json:"darkSkill,omitempty"`
	EnfeeblingSkill       int `json:"enfeeblingSkill,omitempty"`
	ElementalSkill        int `json:"elementalSkill,omitempty"`
	EnhancingSkill        int `json:"enhancingSkill,omitempty"`
	SingingSkill          int `json:"singingSkill,omitempty"`
	StringInstrumentSkill int `json:"stringInstrumentSkill,omitempty"`
	WindInstrumentSkill   int `json:"windInstrumentSkill,omitempty"`
	ClubSkill             int `json:"clubSkill,omitempty"`
	StaffSkill            int `json:"staffSkill,omitempty"`
	DaggerSkill           int `json:"daggerSkill,omitempty"`
	PolearmSkill          int `json:"polearmSkill,omitempty"`
	MarksmanshipSkill     int `json:"marksmanshipSkill,omitempty"`
	EnhacingSkill         int `json:"enhacingSkill,omitempty"`
	ParryingSkill         int `json:"parryingSkill,omitempty"`
}
